python3 converted
linuxmint/live-installer pull request #114
Opened 2020-05-22 22:25 UTC by paledega

LMDE installer python3 convert.

2020-05-22 22:26 UTC, paledega commented on usr/lib/live-installer/frontend/gtk_interface.py
> -        if selection.count_selected_rows > 0:
It not related with python3. I think

2020-05-22 22:27 UTC, paledega commented on usr/lib/live-installer/installer.py
> +        #sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
It is not needed for python3

2020-05-22 22:44 UTC, TheDoop commented
Nice

2020-05-22 23:12 UTC, paledega commented
We fixed gui bugs
now we must fix installation process bugs

2020-05-22 23:26 UTC, paledega commented
![image](https://user-images.githubusercontent.com/38860643/82715618-7ec96c80-9c83-11ea-8079-5d3621dff01d.png)

I am testing on LMDE4 iso.
We have only byte-like object and str issue

2020-05-22 23:36 UTC, sulincix commented
Ohh
@paledega good job

2020-05-22 23:41 UTC, paledega commented on usr/lib/live-installer/partitioning.py
> +            partition_set = tuple(free_space_partition + primary_partitions + logical_partitions + raid_partitions + lvm_partitions)
this changes fixed type error bug

2020-05-22 23:42 UTC, paledega commented on usr/lib/live-installer/partitioning.py
> +            size, free, self.used_percent, mount_point = str(getoutput("df {0} | grep '^{0}' | awk '{{print $2,$4,$5,$6}}' | tail -1".format(self.path)).split(None, 3))
moun_point variable must be string. not byte-like object

2020-05-22 23:43 UTC, paledega commented on usr/lib/live-installer/partitioning.py
> +            self.used_percent = self.used_percent.strip(b'%') or 0
split value must be a byte-like character

2020-05-22 23:43 UTC, paledega commented on usr/lib/live-installer/partitioning.py
> +            elements = str(line).strip().split(" ")
this is better than old code I think

2020-05-24 00:59 UTC, paledega commented
I removed webkit based parts and keyboard preview.

2020-05-24 01:01 UTC, paledega commented
main installation empty now. We should add image.

2020-05-24 01:03 UTC, paledega commented
https://github.com/linuxmint/live-installer/pull/114/commits/62fcfc83ec47db0d22b1ac4f7918050b2f0e5c15
this commit bugless and full feature code. newest commits are remove some parts. I am gonna add again.

2021-02-06 17:41 UTC, sulincix commented
We are forking live-intaller called as "17g"

![image](https://user-images.githubusercontent.com/55052890/107125522-67c6bb00-68a2-11eb-910f-eb22e33ba660.png)

I think Linux mint (ubuntu or debian edition) can use our fork.

source code: https://gitlab.com/ggggggggggggggggg/17g

2021-05-21 06:15 UTC, sulincix commented
https://github.com/linuxmint/live-installer/issues/117

2021-07-16 05:52 UTC, JulianGro requested changes
I was wondering why this hasn't been merged yet.
After a quick look:
    - debian/ folder has been removed
    - the installation slideshow has been removed
    - keyboard layout preview images have been removed?
    - systemd services that used by the live system have been removed
    - generally a lot of changes that are unrelated to a Python3 upgrade and should really be in different PRs
Now I know why this hasn't been merged yet..

2022-01-14 12:46 UTC, clefebvre commented
It's hard to merge PRs when they're not modular.

This will help though. Thanks @paledega, @sulincix and everyone involved.

2022-01-14 14:33 UTC, closed without merging